name: Node CI
on:
  push:
    branches:
      - main
jobs:
  build-publish:
    name: build-publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.0.0
      - name: Build
        run: |
          npm install
          npm run build
      - name: Publish if version has been updated
        uses: pascalgn/npm-publish-action@1.3.3
        with:
          tag_name: 'v%s'
          tag_message: 'v%s'
          commit_pattern: "^Release (\\S+)"
          workspace: '.'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}